version: "3.6"

services:

  portfolio:
    build: 
      context: ./portfolio
    depends_on:
      - service
      - wordpress
    ports:
      - "5000:8080"
    volumes:
      - ./portfolio/build:/usr/share/nginx/html
    networks:
      - cujo

  service: 
    build:
      context: ./service
    expose:     
      - 5001
    env_file:
      - ./service/.env
    environment: 
      - WORDPRESS_CLIENT_ID=dev
      - WORDPRESS_CLIENT_SECRET=dev_secret
    volumes:
      - ./service/data.json:/cujo/data.json
      - ./service/.env:/cujo/.env
    networks:
      - cujo

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - cujo

  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - cujo

volumes:
  db_data: {}

networks:
  cujo: