version: "3.6"

services:
  portfolio:
    build:
      context: ./portfolio
    depends_on:
      - service
    ports:
      - "5000:8080"
    volumes:
      - ./portfolio/build:/usr/share/nginx/html
    networks:
      - cujo

  service:
    build:
      context: ./service
    expose:
      - 5001
    env_file:
      - ./service/.env
    volumes:
      - ./service/data.json:/cujo/data.json
      - ./service/.env:/cujo/.env
    networks:
      - cujo

networks:
  cujo:
