version: "3.6"

services:

  portfolio:
    build: 
      context: ./portfolio
    ports:
      - "5000:8080"
    environment:
      - WORDPRESS_HOST=http://localhost:8000
    volumes:
      - ./portfolio/build:/usr/share/nginx/html
      - ./portfolio/env.sh:/usr/share/nginx/html/env.sh
      - ./portfolio/app.env:/usr/share/nginx/html/app.env
    networks:
      - wordpress

  service: 
    build:
      context: ./service
    expose:     
     - 5001
    env_file:
      - ./service/.env
    networks:
      - wordpress

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - wordpress

volumes:
  db_data: {}

networks:
  wordpress: