version: "3.6"

services:
  portfolio:
    platform: linux/amd64
    build:
      context: ./portfolio_next
      args: 
        - CUJO_SERVICE_URL=https://gql.danclarke.dev
    depends_on:
      - service
    ports:
      - "3000:3000"
      - "3001:3001" # assets
    environment:
      - CUJO_SERVICE_URL=http://service:5001
      - CUJO_REVALIDATE_SECRET=12345
    networks:
      - cujo

  service:
    build:
      context: ./service
    ports:
      - "5001:5001"
    expose:
      - 5001
    env_file:
      - ./service/.env
      - ./service/.sensitive-env
    volumes:
      - ./service/data.json:/cujo/data.json
      - ./service/.env:/cujo/.env
      - ./service/.sensitive-env:/cujo/.sensitive-env
    networks:
      - cujo

networks:
  cujo:
