version: '3.6'

services: 

  client: 
    build: ./client
    ports:
      - "3001:4000" # nodemon / node
      - "8080:8080" # webpack-dev-server
    volumes: 
      - ./client/src:/usr/src/app/src:rw
      - ./client/node_modules:/usr/src/app/node_modules
    networks: 
      - server
    command: npm run start:docker

  server: 
    build: ./server
    ports:
      - "3002:4000" # nodemon / node
    depends_on:
      - mongo
    volumes: 
      - ./server/src:/usr/src/app/src:rw
      - ./server/index.js:/usr/src/app/index.js:rw
    networks: 
      - mongodb
      - server
    env_file: 
      - ./server/server.env
    environment:
      - MONGOHOST=mongo # override the mongo host
      - NODEENV=docker # override the node env
    command: npm run start:dev

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodb:/data/db
      - ./storage/mongo/mongo-setup.js:/docker-entrypoint-initdb.d/mongo-setup.js:ro
    networks: 
      - mongodb
    ports:
      - "27017:27017"   
    env_file: 
      - ./storage/mongo/mongo.env

  minio:
    image: minio/minio
    container_name: minioserver
    ports:
      - 9001:9000
    env_file:
      - ./storage/minio/minio.env
    command: server /data
    volumes:
      - minio:/root/.minio/ 
    networks: 
      - minio
      
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    env_file:
      - ./storage/minio/minio.env
    networks: 
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 2;
      /usr/bin/mc config host add devminio http://minio:9000 $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY};
      /usr/bin/mc mb devminio/devpublic;
      /usr/bin/mc policy download devminio/devpublic;
      exit 0;"

volumes:
  mongodb: 
  minio:

networks: 
  mongodb:
  minio: 
  server: