version: '3.6'

services: 
  client: 
    build: ./client
    ports:
      - "3001:4000"
      - "8080:8080"
    volumes: 
      - ./client/src:/usr/src/app/src:rw
      - ./client/node_modules:/usr/src/app/node_modules
    command: npm run start:watch
  server: 
    build: ./server
    ports:
      - "3002:4000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    # volumes:
    #   - .data:/data/db
    ports:
      - "27017:27017"