version: '3.6'

services:

  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server
    volumes:
      - ./client/build:/usr/share/nginx/html
    networks:
      - server

  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - mongodb
      - server
    env_file:
      - ./server/.env
    environment:
      - MONGO_HOST=mongo # override the mongo host

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodb:/data/db
      - ./storage/mongo/mongo-setup.js:/docker-entrypoint-initdb.d/mongo-setup.js:ro
    networks:
      - mongodb
    ports:
      - "27017:27017"
    env_file:
      - ./storage/mongo/mongo.env

volumes:
  mongodb:
  minio:

networks:
  mongodb:
  minio:
  server: