version: '3'
services: 
  client: 
    build: ./client
    restart: always
    ports:
      - "3001:4000"
  server: 
    build: ./server
    restart: always
    ports:
      - "3002:4000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    # volumes:
    #   - .data:/data/db
    ports:
      - "27017:27017"