version: "3.6"

services:
  reverseproxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./docker/certs:/etc/nginx/certs:ro
    networks:
      - proxy

  ssl-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ssl-companion
    volumes:
      - ./docker/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - reverseproxy
    depends_on:
      - reverseproxy
    networks:
      - proxy

  portfolio:
    image: dclarkious/cujo-portfolio:latest
    container_name: portfolio
    restart: always
    depends_on:
      - reverseproxy
    expose:
      - 8080
    environment:
      - WORDPRESS_HOST=https://blog.${DOMAIN}
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=dc@${DOMAIN}
    networks:
      - wordpress
      - proxy

  wordpress:
    image: wordpress:latest
    restart: always
    depends_on:
      - db
      - reverseproxy
    expose:
      - 80
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_USER_NAME}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - VIRTUAL_HOST=blog.${DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=blog.${DOMAIN}
      - LETSENCRYPT_EMAIL=dc@${DOMAIN}
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - wordpress
      - proxy

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_USER_NAME}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    networks:
      - wordpress

volumes:
  db_data: {}

networks:
  wordpress:
  proxy:
