version: "3.6"

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - cujo

  reverseproxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./docker/certs:/etc/nginx/certs:ro
    networks:
      - cujo

  ssl-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ssl-companion
    volumes:
      - ./docker/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - reverseproxy
    depends_on:
      - reverseproxy
    networks:
      - cujo

  portfolio:
    image: dclarkious/cujo-portfolio:latest
    container_name: portfolio
    restart: always
    depends_on:
      - reverseproxy
      - service
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=dc@${DOMAIN}
      - CUJO_SERVICE_URL=${CUJO_SERVICE_URL}
    networks:
      - cujo

  service:
    image: dclarkious/cujo-rust:latest
    container_name: service
    restart: always
    expose:
      - 5001
    environment:
      - VIRTUAL_HOST=${API_DOMAIN}
      - VIRTUAL_PORT=5001
      - LETSENCRYPT_HOST=${API_DOMAIN}
      - LETSENCRYPT_EMAIL=dc@${DOMAIN}
      - BLOG_HOST=${BLOG_HOST}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - SPACE_ID=${SPACE_ID}
      - ENVIRONMENT=${ENVIRONMENT}
      - AUTH_URL=${AUTH_URL}
      - AUTHORITY=${AUTHORITY}
      - AUDIENCE=${AUDIENCE}
      - SELF_REDIRECT=${SELF_REDIRECT}
    networks:
      - cujo

networks:
  cujo:
