version: "3.6"

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - cujo

  reverseproxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs 
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - cujo

  ssl-companion:
    image: nginxproxy/acme-companion
    container_name: ssl-companion
    volumes_from: nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=dc@${DOMAIN}
    depends_on:
      - reverseproxy
    networks:
      - cujo

  portfolio:
    image: dclarkious/cujo-portfolio:latest
    container_name: portfolio
    restart: always
    depends_on:
      - reverseproxy
      - service
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=dc@${DOMAIN}
      - CUJO_SERVICE_URL=${CUJO_SERVICE_URL}
      - CUJO_REVALIDATE_SECRET=${CUJO_REVALIDATE_SECRET}
    networks:
      - cujo

  service:
    image: dclarkious/cujo-rust:latest
    container_name: service
    restart: always
    expose:
      - 5001
    environment:
      - VIRTUAL_HOST=${API_DOMAIN}
      - VIRTUAL_PORT=5001
      - LETSENCRYPT_HOST=${API_DOMAIN}
      - LETSENCRYPT_EMAIL=dc@${DOMAIN}
      - RUST_LOG=${RUST_LOG}
      - CUJO_REVALIDATE_URL=${CUJO_REVALIDATE_URL}
      - CUJO_REVALIDATE_SECRET=${CUJO_REVALIDATE_SECRET}
      - BLOG_HOST=${BLOG_HOST}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - SPACE_ID=${SPACE_ID}
      - ENVIRONMENT=${ENVIRONMENT}
      - PUBNUB_PUBLISH_TOKEN=${PUBNUB_PUBLISH_TOKEN}
      - PUBNUB_SUBSCRIBE_TOKEN=${PUBNUB_SUBSCRIBE_TOKEN}
      - PUBNUB_CHANNEL_NAME=${PUBNUB_CHANNEL_NAME}
    networks:
      - cujo

networks:
  cujo:

volumes:
  certs:
  html:
  vhostd:
  acme: