// Generated by https://quicktype.io

export interface Media {
    id:             number;
    date:           string;
    date_gmt:       string;
    guid:           Caption;
    modified:       string;
    modified_gmt:   string;
    slug:           string;
    status:         string;
    type:           string;
    link:           string;
    title:          Caption;
    author:         number;
    comment_status: string;
    ping_status:    string;
    template:       string;
    meta:           any[];
    description:    Caption;
    caption:        Caption;
    alt_text:       string;
    media_type:     string;
    mime_type:      string;
    media_details:  MediaDetails;
    post:           number;
    source_url:     string;
    _links:         Links;
}

export interface Links {
    self:       About[];
    collection: About[];
    about:      About[];
    author:     Author[];
    replies:    Author[];
}

export interface About {
    href: string;
}

export interface Author {
    embeddable: boolean;
    href:       string;
}

export interface Caption {
    rendered: string;
}

export interface MediaDetails {
    width:      number;
    height:     number;
    file:       string;
    sizes:      Sizes;
    image_meta: ImageMeta;
}

export interface ImageMeta {
    aperture:          string;
    credit:            string;
    camera:            string;
    caption:           string;
    created_timestamp: string;
    copyright:         string;
    focal_length:      string;
    iso:               string;
    shutter_speed:     string;
    title:             string;
    orientation:       string;
    keywords:          any[];
}

export interface Sizes {
    medium:    Full;
    thumbnail: Full;
    full:      Full;
}

export interface Full {
    file:       string;
    width:      number;
    height:     number;
    mime_type:  string;
    source_url: string;
}
